# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Q2 import Ui_Q2

class GoQ2(object):
    def __init__(self) :
        object.__init__(self)
        self.Frame = QtWidgets.QFrame()
        self.ui = Ui_Q2()
        self.ui.setupUi(self.Frame)
        self.Frame.show()

class Ui_Q1(object):
    def setupUi(self, Q1):
        Q1.setObjectName("Q1")
        Q1.resize(400, 300)
        self.log = QtWidgets.QPushButton(Q1)
        self.log.setGeometry(QtCore.QRect(130, 120, 131, 61))
        self.log.setObjectName("log")

        self.retranslateUi(Q1)
        QtCore.QMetaObject.connectSlotsByName(Q1)
        self.log.clicked.connect(self.gotosec)
    def retranslateUi(self, Q1):
        _translate = QtCore.QCoreApplication.translate
        Q1.setWindowTitle(_translate("Q1", "Frame"))
        self.log.setText(_translate("Q1", "go to Q2"))
        
    def gotosec(self):
        self.m1 = GoQ2()
        Q1.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Q1 = QtWidgets.QFrame()
    ui = Ui_Q1()
    ui.setupUi(Q1)
    Q1.show()
    sys.exit(app.exec_())
