# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Q3 import Ui_Q3

class GoQ3(object):
    def __init__(self) :
        object.__init__(self)
        self.Frame = QtWidgets.QFrame()
        self.ui = Ui_Q3()
        self.ui.setupUi(self.Frame)
        self.Frame.show()

class Ui_Q2(object):
    def setupUi(self, Q2):
        Q2.setObjectName("Q2")
        Q2.resize(400, 300)
        self.dow = QtWidgets.QPushButton(Q2)
        self.dow.setGeometry(QtCore.QRect(100, 120, 171, 61))
        self.dow.setObjectName("dow")

        self.retranslateUi(Q2)
        QtCore.QMetaObject.connectSlotsByName(Q2)
        self.dow.clicked.connect(self.gotoTHIR)
    
    def retranslateUi(self, Q2):
        _translate = QtCore.QCoreApplication.translate
        Q2.setWindowTitle(_translate("Q2", "Frame"))
        self.dow.setText(_translate("Q2", "go to Q3"))

    def gotoTHIR(self):
        self.m2 = GoQ3()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Q2 = QtWidgets.QFrame()
    ui = Ui_Q2()
    ui.setupUi(Q2)
    Q2.show()
    sys.exit(app.exec_())
