# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame2(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1089, 709)
        Frame.setMinimumSize(QtCore.QSize(1089, 709))
        Frame.setMaximumSize(QtCore.QSize(1089, 709))
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1091, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(60, 30, 961, 211))
        self.widget.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius: 25px;")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, 30, 521, 51))
        self.label_6.setObjectName("label_6")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(290, 280, 711, 381))
        self.scrollArea.setStyleSheet("\n"
"background-color: rgb(221, 221, 221);\n"
"border-radius: 25px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 711, 381))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(60, 280, 211, 271))
        self.scrollArea_2.setStyleSheet("\n"
"background-color: rgb(221, 221, 221);\n"
"border-radius: 25px; ")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 211, 271))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 161, 41))
        self.label_7.setObjectName("label_7")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_5.setGeometry(QtCore.QRect(130, 30, 791, 631))
        self.scrollArea_5.setStyleSheet("\n"
"background-color: rgb(221, 221, 221);\n"
"border-radius: 25px;")
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 791, 631))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_6.setGeometry(QtCore.QRect(120, 70, 841, 171))
        self.scrollArea_6.setStyleSheet("\n"
"background-color: rgb(221, 221, 221);\n"
"border-radius: 25px;")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 841, 171))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(120, 30, 161, 31))
        self.label_10.setObjectName("label_10")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(120, 260, 161, 31))
        self.label_20.setObjectName("label_20")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_7.setGeometry(QtCore.QRect(120, 310, 841, 341))
        self.scrollArea_7.setStyleSheet("\n"
"background-color: rgb(221, 221, 221);\n"
"border-radius: 25px;")
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 841, 341))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_6.setText(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">SEIT</span></p></body></html>"))
        self.label_7.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#1b93e3;\">Upcoming</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Frame", "Stream"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Frame", "Classwork"))
        self.label_10.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#1b93e3;\">Teacher</span></p></body></html>"))
        self.label_20.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#1b93e3;\">Classmates</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Frame", "People"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame2()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
