# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Class_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import MySQLdb
from PyQt5 import QtCore, QtGui, QtWidgets
import m1
tlist=[]
slist=[]

class Ui_Class_Frame(object):
    username=""
    
    def __init__(self , user ):
        self.username = user 
        print(self.username)
    print(username + "  n")
    def setupUi(self, Class_Frame):
        Class_Frame.setObjectName("Class_Frame")
        Class_Frame.resize(994, 661)
        self.logout = QtWidgets.QPushButton(Class_Frame)
        self.logout.setGeometry(QtCore.QRect(840, 20, 121, 41))
        self.logout.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius:10px;\n"
"font: 75 16pt \"Times New Roman\";\n"
"color:white;\n"
"\n"
"")
        conn =  MySQLdb.connect(host="localhost" ,database="class_proj" , user="root" , password="" )
        cursor = conn.cursor()

        cursor.execute("SELECT course.scode ,course.username ,subject.Sname\n"
                       "FROM course Inner JOIN subject ON course.Scode = subject.Scode\n"
                       "Where course.Username = '"+self.username+"'")
        row = cursor.fetchone()

        while row is not None :
            slist.append(row)
            row = cursor.fetchone()


        cursor.execute("SELECT * FROM `subject` WHERE username='"+self.username+"' ")
        row1 = cursor.fetchone()
    
        while row1 is not None :
            tlist.append(row1)
            row1 = cursor.fetchone()
        print(slist, tlist)
        cursor.close()
        conn.close()
        self.logout.setObjectName("logout")
        self.logout.clicked.connect(self.gotologin)
        
        self.escode = QtWidgets.QLineEdit(Class_Frame)
        self.escode.setGeometry(QtCore.QRect(40, 20, 171, 41))
        self.escode.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius:10px;")
        self.escode.setObjectName("escode")
        self.add = QtWidgets.QPushButton(Class_Frame)
        self.add.setGeometry(QtCore.QRect(240, 20, 121, 41))
        self.add.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius:10px;\n"
"font: 75 16pt \"Times New Roman\";\n"
"color:white;\n"
"\n"
"")
        self.add.setObjectName("add")
        self.add.clicked.connect(self.addclass)
        
        self.create = QtWidgets.QPushButton(Class_Frame)
        self.create.setGeometry(QtCore.QRect(510, 20, 181, 41))
        self.create.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius:10px;\n"
"font: 75 16pt \"Times New Roman\";\n"
"color:white;\n"
"\n"
"")
        self.create.setObjectName("create")
        self.teacherclist = QtWidgets.QListWidget(Class_Frame)
        self.teacherclist.setGeometry(QtCore.QRect(120, 130, 256, 371))
        self.teacherclist.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"border-radius:15px;")
        self.teacherclist.setObjectName("teacherclist")
        self.studentclist = QtWidgets.QListWidget(Class_Frame)
        self.studentclist.setGeometry(QtCore.QRect(570, 130, 256, 371))
        self.studentclist.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"border-radius:15px;")
        self.studentclist.setObjectName("studentclist")
        self.estudent = QtWidgets.QPushButton(Class_Frame)
        self.estudent.setGeometry(QtCore.QRect(580, 550, 241, 51))
        self.estudent.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius: 10px;\n"
"font: 75 16pt \"Times New Roman\";\n"
"color:white;")
        self.estudent.setObjectName("estudent")
        self.eteacher = QtWidgets.QPushButton(Class_Frame)
        self.eteacher.setGeometry(QtCore.QRect(120, 550, 241, 51))
        self.eteacher.setStyleSheet("background-color: rgb(27, 147, 227);\n"
"border-radius: 10px;\n"
"font: 75 16pt \"Times New Roman\";\n"
"color:white;")
        self.eteacher.setObjectName("eteacher")

        self.retranslateUi(Class_Frame)
        for t12 in tlist :
            self.teacherclist.addItem(t12[0]+"    "+t12[1])

        for t12 in slist :
            self.studentclist.addItem(t12[0]+"    "+t12[2])
    
        QtCore.QMetaObject.connectSlotsByName(Class_Frame)
        

    def retranslateUi(self, Class_Frame):
        _translate = QtCore.QCoreApplication.translate
        Class_Frame.setWindowTitle(_translate("Class_Frame", "Frame"))
        self.logout.setText(_translate("Class_Frame", "Logout"))
        self.escode.setPlaceholderText(_translate("Class_Frame", "Enter Scode"))
        self.add.setText(_translate("Class_Frame", "ADD"))
        self.create.setText(_translate("Class_Frame", "Create Class"))
        self.estudent.setText(_translate("Class_Frame", "Enter as Student"))
        self.eteacher.setText(_translate("Class_Frame", "Enter as Teacher"))
    def addclass(self):
        print("class is adding")
    
        conn =  MySQLdb.connect(host="localhost" ,database="class_proj" , user="root" , password="" )
        cursor = conn.cursor()
        ins = "INSERT INTO `course` "
        val = " VALUES ('"+self.escode.text()+"', '"+self.username+"');"
        sql = ins + val
        try :
            cursor.execute(sql)
            conn.commit()
            print("successfully adding class")
            
        except:
            conn.rollback()
        cursor.close()
        conn.close()
    def gotologin(self):
        self.C1 = QtWidgets.QFrame()
        self.ui = m1.Ui_Login()
        self.ui.setupUi(self.C1)
        self.C1.show()
        Class_Frame.close()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_Frame = QtWidgets.QFrame()
    ui = Ui_Class_Frame("Utkarsha")
    ui.setupUi(Class_Frame)
    Class_Frame.show()
    sys.exit(app.exec_())
