# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dow_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon
from tkinter import filedialog , messagebox
from classroom import Ui_Frame2
import sys

class GoToClass(object):
    def __init__(self) :
        #object.__init__(self)
        self.Frame = QtWidgets.QFrame()
        self.ui = Ui_Frame2()
        self.ui.setupUi(self.Frame)
        self.Frame.show()

    
class Ui_Frame1(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(736, 537)
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(420, 50, 281, 181))
        self.widget.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.options = QFileDialog.Options()
        self.options |= QFileDialog.DontUseNativeDialog

        self.Submit = QtWidgets.QPushButton(self.widget)
        self.Submit.setGeometry(QtCore.QRect(40, 120, 211, 41))
        self.Submit.setStyleSheet("background-color: rgb(71, 147, 227);\n"
"border-radius: 10px ;")
        self.Submit.setObjectName("Submit")
        self.Submit.clicked.connect(self.button_clicked)
        self.Work = QtWidgets.QPushButton(self.widget)
        self.Work.setGeometry(QtCore.QRect(40, 40, 211, 41))
        self.Work.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px ;")
        self.op = QFileDialog.Options()
        self.Work.setObjectName("Work")
        self.label1 = QtWidgets.QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(50, 90, 191, 16))
        self.label1.setObjectName("label1")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 241, 41))
        self.label_2.setObjectName("label_2")
    
        self.textEdit = QtWidgets.QTextEdit(Frame)
        self.textEdit.setGeometry(QtCore.QRect(60, 250, 641, 131))
        self.textEdit.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius: 10px ;")
        self.textEdit.setObjectName("textEdit")
        self.download = QtWidgets.QPushButton(Frame)
        self.download.setGeometry(QtCore.QRect(370, 400, 131, 41))
        self.download.setStyleSheet("background-color: rgb(71, 147, 227);\n"
"border-radius: 10px ;")
        self.download.setObjectName("download")
        self.download.clicked.connect(self.gotoClass)
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(130, 400, 211, 31))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.Submit.setText(_translate("Frame", "submit"))
        self.Work.setText(_translate("Frame", "+ add your work"))
        self.label1.setText(_translate("Frame", "work.docx"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#4793e3;\">Assignment 1</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  zzx    d f weqf</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">afafafeq </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gt we gwtwertgwe werwd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gdgrgwr ty</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> fgwrgwert </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> w</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rgwergwergwrghwrghwrhr</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p></body></html>"))
        self.download.setText(_translate("Frame", "Download"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#4793e3;\">Assignment1.docx</span></p></body></html>"))

    def gotoClass(self) :
        self.m2 = GoToClass()
        #Frame.close()
            
    def open_file(self):
        self.filename = filedialog.askopenfilename(parent=root,title="Select file",filetypes=(("Image File", "*.PNG"),("All Files", "*.*" )))
        
    
    def button_clicked(self):
        print("Okay")
        self.update()

    def update(self):
        fn= filedialog.askopenfilename(title="Select file",filetypes=(("Image File", "*.PNG"),("All Files", "*.*" )))
        s = 5
        #with open(fn,"rb") as f :
        
        #   data = fn.read()
        print(data)


class App(QWidget):

    def __init__(self):
        super().__init__()
        self.title = 'PyQt5 file dialogs - pythonspot.com'
        self.left = 10
        self.top = 10
        self.width = 640
        self.height = 480
        self.initUI()
    
    def initUI(self):

        self.openFileNameDialog()
        self.openFileNamesDialog()
        self.saveFileDialog()
        
        self.show()
    
    def openFileNameDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self,"QFileDialog.getOpenFileName()", "","All Files (*);;Python Files (*.py)", options=options)
        if fileName:
            print(fileName)
    
    def openFileNamesDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        files, _ = QFileDialog.getOpenFileNames(self,"QFileDialog.getOpenFileNames()", "","All Files (*);;Python Files (*.py)", options=options)
        if files:
            print(files)
    
    def saveFileDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getSaveFileName(self,"QFileDialog.getSaveFileName()","","All Files (*);;Text Files (*.txt)", options=options)
        if fileName:
            print(fileName)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame1()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
