# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Class_Frame #import Ui_Class_Frame
import MySQLdb

class Gotoclass(object):
    def __init__(self,user):
        object.__init__(self)
        self.C1 = QtWidgets.QFrame()
        self.ui = Class_Frame.Ui_Class_Frame(user)
        self.ui.setupUi(self.C1)
        self.C1.show()
        

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(340, 561)
        Login.setMinimumSize(QtCore.QSize(340, 561))
        Login.setMaximumSize(QtCore.QSize(340, 561))
        self.log = QtWidgets.QTabWidget(Login)
        self.log.setGeometry(QtCore.QRect(0, 0, 341, 561))
        self.log.setMinimumSize(QtCore.QSize(341, 561))
        self.log.setMaximumSize(QtCore.QSize(341, 561))
        self.log.setStyleSheet("")
        self.log.setTabPosition(QtWidgets.QTabWidget.North)
        self.log.setUsesScrollButtons(False)
        self.log.setDocumentMode(False)
        self.log.setTabsClosable(False)
        self.log.setMovable(False)
        self.log.setTabBarAutoHide(False)
        self.log.setObjectName("log")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Logbut = QtWidgets.QPushButton(self.tab)
        self.Logbut.setGeometry(QtCore.QRect(80, 330, 191, 51))
        self.Logbut.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"border-radius: 10px ;\n"
"background-color: rgb(71, 147, 227);\n"
"\n"
"}")
        self.Logbut.setText("")
        self.Logbut.setObjectName("Logbut")
        self.Logbut.clicked.connect(self.gtc)
        self.L1 = QtWidgets.QLabel(self.tab)
        self.L1.setGeometry(QtCore.QRect(130, 340, 91, 31))
        self.L1.setStyleSheet("")
        self.L1.setObjectName("L1")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 400, 251, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.tab)
        self.username.setGeometry(QtCore.QRect(80, 160, 191, 31))
        self.username.setStyleSheet("border-radius: 7px ;\n"
"background-color: rgb(197, 197, 197);")
        self.username.setText("")
        self.username.setObjectName("username")
        self.userLabel = QtWidgets.QLabel(self.tab)
        self.userLabel.setGeometry(QtCore.QRect(90, 200, 121, 21))
        self.userLabel.setObjectName("userLabel")
        self.password = QtWidgets.QLineEdit(self.tab)
        self.password.setGeometry(QtCore.QRect(80, 250, 191, 31))
        self.password.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px ;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.passwordlabel = QtWidgets.QLabel(self.tab)
        self.passwordlabel.setGeometry(QtCore.QRect(90, 290, 111, 21))
        self.passwordlabel.setObjectName("passwordlabel")
        self.logo = QtWidgets.QLabel(self.tab)
        self.logo.setGeometry(QtCore.QRect(130, 20, 81, 61))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../logo.png"))
        self.logo.setObjectName("logo")
        self.log.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.user = QtWidgets.QLineEdit(self.tab_2)
        self.user.setGeometry(QtCore.QRect(60, 100, 221, 31))
        self.user.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.user.setObjectName("user")
        self.passwoed = QtWidgets.QLineEdit(self.tab_2)
        self.passwoed.setGeometry(QtCore.QRect(60, 290, 221, 31))
        self.passwoed.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.passwoed.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwoed.setObjectName("passwoed")
        self.confpass = QtWidgets.QLineEdit(self.tab_2)
        self.confpass.setGeometry(QtCore.QRect(60, 360, 221, 31))
        self.confpass.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.confpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confpass.setObjectName("confpass")
        self.email = QtWidgets.QLineEdit(self.tab_2)
        self.email.setGeometry(QtCore.QRect(60, 220, 221, 31))
        self.email.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.email.setObjectName("email")
        self.userlabel = QtWidgets.QLabel(self.tab_2)
        self.userlabel.setGeometry(QtCore.QRect(70, 130, 121, 21))
        self.userlabel.setObjectName("userlabel")
        self.email_label = QtWidgets.QLabel(self.tab_2)
        self.email_label.setGeometry(QtCore.QRect(70, 250, 121, 21))
        self.email_label.setObjectName("email_label")
        self.pass_label = QtWidgets.QLabel(self.tab_2)
        self.pass_label.setGeometry(QtCore.QRect(70, 320, 121, 21))
        self.pass_label.setObjectName("pass_label")
        self.cp_label = QtWidgets.QLabel(self.tab_2)
        self.cp_label.setGeometry(QtCore.QRect(70, 390, 121, 21))
        self.cp_label.setObjectName("cp_label")
        self.Signup = QtWidgets.QPushButton(self.tab_2)
        self.Signup.setGeometry(QtCore.QRect(70, 430, 211, 51))
        self.Signup.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"border-radius: 10px ;\n"
"background-color: rgb(71, 147, 227);\n"
"\n"
"}")
        self.Signup.setText("")
        self.Signup.setObjectName("Signup")
        self.Signup.clicked.connect(self.sgup)
        self.signUplabel = QtWidgets.QLabel(self.tab_2)
        self.signUplabel.setGeometry(QtCore.QRect(120, 440, 111, 31))
        self.signUplabel.setStyleSheet("")
        self.signUplabel.setObjectName("signUplabel")
        self.logo_2 = QtWidgets.QLabel(self.tab_2)
        self.logo_2.setGeometry(QtCore.QRect(130, 20, 81, 61))
        self.logo_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("../logo.png"))
        self.logo_2.setObjectName("logo_2")
        self.firstname = QtWidgets.QLineEdit(self.tab_2)
        self.firstname.setGeometry(QtCore.QRect(60, 160, 61, 31))
        self.firstname.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.firstname.setObjectName("firstname")
        self.lastname = QtWidgets.QLineEdit(self.tab_2)
        self.lastname.setGeometry(QtCore.QRect(220, 160, 61, 31))
        self.lastname.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.lastname.setObjectName("lastname")
        self.firstlabel = QtWidgets.QLabel(self.tab_2)
        self.firstlabel.setGeometry(QtCore.QRect(60, 190, 61, 21))
        self.firstlabel.setObjectName("firstlabel")
        self.Last_label = QtWidgets.QLabel(self.tab_2)
        self.Last_label.setGeometry(QtCore.QRect(220, 190, 71, 21))
        self.Last_label.setObjectName("Last_label")
        self.middlename = QtWidgets.QLineEdit(self.tab_2)
        self.middlename.setGeometry(QtCore.QRect(140, 160, 61, 31))
        self.middlename.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.middlename.setObjectName("middlename")
        self.middle_label = QtWidgets.QLabel(self.tab_2)
        self.middle_label.setGeometry(QtCore.QRect(130, 190, 71, 21))
        self.middle_label.setObjectName("middle_label")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(40, 495, 241, 21))
        self.label.setObjectName("label")
        self.log.addTab(self.tab_2, "")

        self.retranslateUi(Login)
        self.log.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Frame"))
        self.L1.setText(_translate("Login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#fefefe;\">Login</span></p></body></html>"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.username.setPlaceholderText(_translate("Login", "username"))
        self.userLabel.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">   Username</span></p></body></html>"))
        self.password.setPlaceholderText(_translate("Login", "password"))
        self.passwordlabel.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Password</span></p></body></html>"))
        self.log.setTabText(self.log.indexOf(self.tab), _translate("Login", "Login"))
        self.user.setPlaceholderText(_translate("Login", "username"))
        self.passwoed.setPlaceholderText(_translate("Login", "password"))
        self.confpass.setPlaceholderText(_translate("Login", "confirm password"))
        self.email.setPlaceholderText(_translate("Login", "email@e.com"))
        self.userlabel.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">   Username</span></p></body></html>"))
        self.email_label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Email</span></p></body></html>"))
        self.pass_label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Password</span></p></body></html>"))
        self.cp_label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Confirm Password</span></p></body></html>"))
        self.signUplabel.setText(_translate("Login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#fefefe;\">Sign Up</span></p></body></html>"))
        self.firstname.setPlaceholderText(_translate("Login", "Name"))
        self.lastname.setPlaceholderText(_translate("Login", "surname"))
        self.firstlabel.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">First Name</span></p></body></html>"))
        self.Last_label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Last Name</span></p></body></html>"))
        self.middlename.setPlaceholderText(_translate("Login", "Name"))
        self.middle_label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Middle Name</span></p></body></html>"))
        self.label.setText(_translate("Login", "<html><head/><body><p><br/></p></body></html>"))
        self.log.setTabText(self.log.indexOf(self.tab_2), _translate("Login", "Sign up"))


    def gtc(self):
        
        self.use1 = self.username.text()
        try:
            conn =  MySQLdb.connect(host="localhost" ,database="class_proj" , user="root" , password="" )
            cursor = conn.cursor()
            cursor.execute("select * from User where username='"+self.use1+"' and password='"+self.password.text()+"'")
            row = cursor.fetchone()
        except:
            print("error in sql")
        finally:
            cursor.close()
            conn.close()
            
        if row is not None :
            self.C2=Gotoclass(self.use1)
            print(row)
            Login.close()
        else:
            self.label_2.setText("Invalid Username or Password")

    def sgup(self):
        
        print("executing")
        
        self.use1 = self.user.text()
        self.g1 = self.email.text()
        self.p1 = self.passwoed.text()
        self.f1 = self.firstname.text()
        self.m1 = self.middlename.text()
        self.l1 = self.lastname.text()
        conn =  MySQLdb.connect(host="localhost" ,database="class_proj" , user="root" , password="" )
        cursor = conn.cursor()
        ins = "INSERT INTO `user` (`Username`, `gmail`, `Password`, `Fname`, `Mname`, `Lname`)  "
        val = " VALUES ('"+self.use1+"', '"+self.g1+"','"+self.p1+"','"+self.f1+"','"+self.m1+"','"+self.l1+"');"
        sql = ins + val
        try :
            cursor.execute(sql)
            conn.commit()
            print("successfully signup")
            self.label.setText("successfully signup")
        except:
            conn.rollback()
            print("username is already exist")
            self.label.setText("username is already exist")
        cursor.close()
        conn.close()

            
        

        
  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QFrame()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
