# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(342, 559)
        self.login = QtWidgets.QTabWidget(Frame)
        self.login.setGeometry(QtCore.QRect(0, 0, 341, 561))
        self.login.setMinimumSize(QtCore.QSize(341, 561))
        self.login.setMaximumSize(QtCore.QSize(341, 561))
        self.login.setStyleSheet("")
        self.login.setTabPosition(QtWidgets.QTabWidget.North)
        self.login.setUsesScrollButtons(False)
        self.login.setDocumentMode(False)
        self.login.setTabsClosable(False)
        self.login.setMovable(False)
        self.login.setTabBarAutoHide(False)
        self.login.setObjectName("login")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Logbut = QtWidgets.QPushButton(self.tab)
        self.Logbut.setGeometry(QtCore.QRect(80, 350, 191, 51))
        self.Logbut.setStyleSheet("\n"
"QPushButton{\n"
"box-shadow: 10px 10px rgb(61, 61, 61);\n"
"border-radius: 10px ;\n"
"background-color: rgb(71, 147, 227);\n"
"\n"
"}")
        self.Logbut.setText("")
        self.Logbut.setObjectName("Logbut")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(110, 360, 121, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 490, 51, 16))
        self.label_2.setStyleSheet("background-color: rgb(71, 147, 227);\n"
"border-radius:5px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.tab)
        self.username.setGeometry(QtCore.QRect(80, 160, 191, 31))
        self.username.setStyleSheet("border-radius: 7px ;\n"
"background-color: rgb(197, 197, 197);")
        self.username.setText("")
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 121, 21))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.tab)
        self.password.setGeometry(QtCore.QRect(80, 250, 191, 31))
        self.password.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px ;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(90, 290, 111, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(130, 20, 81, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../logo.png"))
        self.label_5.setObjectName("label_5")
        self.login.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.user = QtWidgets.QLineEdit(self.tab_2)
        self.user.setGeometry(QtCore.QRect(60, 100, 221, 31))
        self.user.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.user.setObjectName("user")
        self.password_2 = QtWidgets.QLineEdit(self.tab_2)
        self.password_2.setGeometry(QtCore.QRect(60, 290, 221, 31))
        self.password_2.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.confpass = QtWidgets.QLineEdit(self.tab_2)
        self.confpass.setGeometry(QtCore.QRect(60, 360, 221, 31))
        self.confpass.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.confpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confpass.setObjectName("confpass")
        self.email = QtWidgets.QLineEdit(self.tab_2)
        self.email.setGeometry(QtCore.QRect(60, 220, 221, 31))
        self.email.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.email.setObjectName("email")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(70, 130, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(70, 250, 121, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(70, 320, 121, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(70, 390, 121, 21))
        self.label_14.setObjectName("label_14")
        self.Logbut_3 = QtWidgets.QPushButton(self.tab_2)
        self.Logbut_3.setGeometry(QtCore.QRect(70, 430, 201, 51))
        self.Logbut_3.setStyleSheet("\n"
"QPushButton{\n"
"box-shadow: 10px 10px rgb(61, 61, 61);\n"
"border-radius: 10px ;\n"
"background-color: rgb(71, 147, 227);\n"
"\n"
"}")
        self.Logbut_3.setText("")
        self.Logbut_3.setObjectName("Logbut_3")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(120, 440, 121, 31))
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(130, 20, 81, 61))
        self.label_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../logo.png"))
        self.label_16.setObjectName("label_16")
        self.firstname = QtWidgets.QLineEdit(self.tab_2)
        self.firstname.setGeometry(QtCore.QRect(60, 160, 61, 31))
        self.firstname.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.firstname.setObjectName("firstname")
        self.lastname = QtWidgets.QLineEdit(self.tab_2)
        self.lastname.setGeometry(QtCore.QRect(220, 160, 61, 31))
        self.lastname.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.lastname.setObjectName("lastname")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(60, 190, 61, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(220, 190, 71, 21))
        self.label_18.setObjectName("label_18")
        self.firstname_2 = QtWidgets.QLineEdit(self.tab_2)
        self.firstname_2.setGeometry(QtCore.QRect(140, 160, 61, 31))
        self.firstname_2.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"border-radius: 7px;")
        self.firstname_2.setObjectName("firstname_2")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(130, 190, 71, 21))
        self.label_19.setObjectName("label_19")
        self.login.addTab(self.tab_2, "")

        self.retranslateUi(Frame)
        self.login.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#fefefe;\">Login</span></p></body></html>"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Login</span></p></body></html>"))
        self.username.setPlaceholderText(_translate("Frame", "username"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">   Username</span></p></body></html>"))
        self.password.setPlaceholderText(_translate("Frame", "password"))
        self.label_4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Password</span></p></body></html>"))
        self.login.setTabText(self.login.indexOf(self.tab), _translate("Frame", "Login"))
        self.user.setPlaceholderText(_translate("Frame", "username"))
        self.password_2.setPlaceholderText(_translate("Frame", "password"))
        self.confpass.setPlaceholderText(_translate("Frame", "confirm password"))
        self.email.setPlaceholderText(_translate("Frame", "email@e.com"))
        self.label_11.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">   Username</span></p></body></html>"))
        self.label_12.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Email</span></p></body></html>"))
        self.label_13.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Password</span></p></body></html>"))
        self.label_14.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Confirm Password</span></p></body></html>"))
        self.label_15.setText(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#fefefe;\">Sign Up</span></p></body></html>"))
        self.firstname.setPlaceholderText(_translate("Frame", "Name"))
        self.lastname.setPlaceholderText(_translate("Frame", "surname"))
        self.label_17.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">First Name</span></p></body></html>"))
        self.label_18.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Last Name</span></p></body></html>"))
        self.firstname_2.setPlaceholderText(_translate("Frame", "Name"))
        self.label_19.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600; color:#4793e3;\">Middle Name</span></p></body></html>"))
        self.login.setTabText(self.login.indexOf(self.tab_2), _translate("Frame", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
